### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by sukeshjain** [cucumber/gherkin2#346]
Is it possible to have a new release of this project as it has lot of fixes done since last release before this project got shelved?

**Comment by aslakhellesoy** [comment]
@sukeshjain what cucumber flavour are you using? Ruby? Java? JavaScript? Other?

**Comment by sukeshjain** [comment]
Java

**Comment by aslakhellesoy** [comment]
I don't think we will release a new version of gherkin2 - we want to focus on getting gherkin3 into Cucumber-JVM instead.
